Repository kubernetes-sigs/controller-tools, pull requests merged in 2018-07, with the labels that each got.

#28 fix test for core type controller
  pkg/scaffold/controller/controllertest.go
  test/pkg/controller/firstmate/firstmate_controller_test.go
  test/pkg/controller/frigate/frigate_controller_test.go
  test/pkg/controller/kraken/kraken_controller_test.go
  test/pkg/controller/namespace/namespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 added rbac manifests generation pkg and CLI
  cmd/controller-gen/main.go
  pkg/generate/rbac/manifests.go
  pkg/generate/rbac/parser.go
  pkg/generate/rbac/parser_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 controller-gen: added rbac generation
  cmd/controller-gen/main.go
  pkg/generate/rbac/manifests.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#27 Add CRD generation command
  cmd/crd/cmd/generate.go
  cmd/crd/cmd/root.go
  cmd/crd/main.go
  pkg/crd/generator/generator.go
  pkg/crd/util/util.go
  pkg/internal/codegen/parse/apis.go
  pkg/internal/codegen/parse/context.go
  pkg/internal/codegen/parse/controllers.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/index.go
  pkg/internal/codegen/parse/parser.go
  pkg/internal/codegen/parse/rbac.go
  pkg/internal/codegen/parse/util.go
  pkg/internal/codegen/types.go
  pkg/scaffold/scaffold.go
  pkg/util/util.go
  test.sh
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#38 added manifests target in Makefile for CRD/RBAC generation
  pkg/scaffold/project/makefile.go
  test/Makefile
Labels: approved, cncf-cla: yes, lgtm

#37 added controller-tools dependency for generated project
  pkg/scaffold/project/gopkg.go
  test/Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#36 controller-gen: integrate crd generator
  cmd/controller-gen/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#34 Add default rbac annotation in resource
  pkg/scaffold/controller/controller.go
  test/pkg/controller/firstmate/firstmate_controller.go
  test/pkg/controller/frigate/frigate_controller.go
  test/pkg/controller/kraken/kraken_controller.go
  test/pkg/controller/namespace/namespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#40 Moved rbac/crd manifests generation to makefile
  cmd/controller-scaffold/cmd/api.go
  cmd/controller-scaffold/cmd/project.go
  pkg/generate/rbac/manifests.go
  pkg/scaffold/manager/config.go
  pkg/scaffold/project/makefile.go
  pkg/scaffold/resource/resource_test.go
  test/Makefile
  test/config/crds/creatures_v2alpha1_kraken.yaml
  test/config/crds/crew_v1_firstmate.yaml
  test/config/crds/ship_v1beta1_frigate.yaml
  test/config/manager/creatures_role_rbac.yaml
  test/config/manager/crew_role_rbac.yaml
  test/config/manager/crew_rolebinding_rbac.yaml
  test/config/manager/manager.yaml
  test/config/manager/ship_role_rbac.yaml
  test/config/manager/ship_rolebinding_rbac.yaml
  test/config/rbac/rbac_role.yaml
  test/config/rbac/rbac_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 change TestStorage function to TestStorage<Kind>
  pkg/scaffold/resource/typestest.go
  test/pkg/apis/creatures/v2alpha1/kraken_types_test.go
  test/pkg/apis/crew/v1/firstmate_types_test.go
  test/pkg/apis/ship/v1beta1/frigate_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#43 Don't gitignore generated files under vendor
  pkg/scaffold/project/gitignore.go
  test/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 kustomization.yaml and kustomize image patch scaffolding
  cmd/controller-scaffold/cmd/project.go
  pkg/scaffold/project/kustomize.go
  pkg/scaffold/project/kustomize_image_patch.go
  pkg/scaffold/project/project_test.go
  test/config/default/kustomization.yaml
  test/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 scaffold crd samples
  cmd/controller-scaffold/cmd/api.go
  pkg/scaffold/resource/crd_sample.go
  pkg/scaffold/resource/resource_test.go
  test/config/samples/creatures_v2alpha1_kraken.yaml
  test/config/samples/crew_v1_firstmate.yaml
  test/config/samples/ship_v1beta1_frigate.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#45 fixed api-group and resource field in RBAC annotation
  pkg/scaffold/controller/controller.go
  test/config/rbac/rbac_role.yaml
  test/pkg/controller/firstmate/firstmate_controller.go
  test/pkg/controller/frigate/frigate_controller.go
  test/pkg/controller/kraken/kraken_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#47 controller-tools path in Makefile scaffolding
  cmd/controller-scaffold/cmd/project.go
  generated_golden.sh
  pkg/scaffold/project/makefile.go
  pkg/scaffold/project/project_test.go
  test/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#46 added make deploy target with kustomize integration
  pkg/scaffold/project/kustomize.go
  pkg/scaffold/project/kustomize_image_patch.go
  pkg/scaffold/project/makefile.go
  test/Makefile
  test/config/default/kustomization.yaml
  test/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#48 fixed the comment to trigger code regeneration
  pkg/scaffold/resource/types.go
  test/pkg/apis/creatures/v2alpha1/kraken_types.go
  test/pkg/apis/crew/v1/firstmate_types.go
  test/pkg/apis/ship/v1beta1/frigate_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#49 fixed fsnotify dependency in gopkg toml
  pkg/scaffold/project/gopkg.go
  test/Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#50 scaffold image namge in MAKEFILE
  pkg/scaffold/project/makefile.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 pin deps in Gopkg.toml file for generated projects
  cmd/controller-gen/main.go
  pkg/scaffold/project/gopkg.go
  test/Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 Skip openapi schema generation for map-type
  cmd/controller-gen/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
