Repository kubernetes-sigs/controller-tools, pull requests merged in 2018-06, with the labels that each got.

#1 Setup travis for controller-tools
  .travis.yml
  pkg/generate/doc.go
  pkg/scaffold/doc.go
  test.sh
Labels: cncf-cla: yes, size/L

#7 Scaffold a new project
  pkg/scaffold/input/input.go
  pkg/scaffold/project/boilerplate.go
  pkg/scaffold/project/gitignore.go
  pkg/scaffold/project/gopkg.go
  pkg/scaffold/project/makefile.go
  pkg/scaffold/project/project.go
  pkg/scaffold/scaffold.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#11 Cleanup readme and test.sh
  README.md
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#13 Run scaffold commands to generate baseline for testing
  test/.gitignore
  test/Dockerfile
  test/Gopkg.toml
  test/Makefile
  test/PROJECT
  test/cmd/manager/main.go
  test/config/crds/crew_v1_firstmate.yaml
  test/config/crds/ship_v1beta1_frigate.yaml
  test/config/manager/crew_role_rbac.yaml
  test/config/manager/crew_rolebinding_rbac.yaml
  test/config/manager/manager.yaml
  test/config/manager/ship_role_rbac.yaml
  test/config/manager/ship_rolebinding_rbac.yaml
  test/hack/boilerplate.go.txt
  test/pkg/apis/addtoscheme_crew_v1.go
  test/pkg/apis/addtoscheme_ship_v1beta1.go
  test/pkg/apis/apis.go
  test/pkg/apis/crew/group.go
  test/pkg/apis/crew/v1/doc.go
  test/pkg/apis/crew/v1/firstmate_types.go
  test/pkg/apis/crew/v1/firstmate_types_test.go
  test/pkg/apis/crew/v1/register.go
  test/pkg/apis/crew/v1/v1_suite_test.go
  test/pkg/apis/ship/group.go
  test/pkg/apis/ship/v1beta1/doc.go
  test/pkg/apis/ship/v1beta1/frigate_types.go
  test/pkg/apis/ship/v1beta1/frigate_types_test.go
  test/pkg/apis/ship/v1beta1/register.go
  test/pkg/apis/ship/v1beta1/v1beta1_suite_test.go
  test/pkg/controller/add_firstmate.go
  test/pkg/controller/add_frigate.go
  test/pkg/controller/controller.go
  test/pkg/controller/firstmate/firstmate_controller.go
  test/pkg/controller/firstmate/firstmate_controller_suite_test.go
  test/pkg/controller/firstmate/firstmate_controller_test.go
  test/pkg/controller/frigate/frigate_controller.go
  test/pkg/controller/frigate/frigate_controller_suite_test.go
  test/pkg/controller/frigate/frigate_controller_test.go
  test/vendor
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#12 Add reference command implementation to use scaffold libraries
  cmd/controller-scaffold/cmd/api.go
  cmd/controller-scaffold/cmd/project.go
  cmd/controller-scaffold/cmd/root.go
  cmd/controller-scaffold/cmd/stdin.go
  cmd/controller-scaffold/doc.go
  cmd/controller-scaffold/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8 Scaffold out a Resource for an API
  pkg/scaffold/resource/addtoscheme.go
  pkg/scaffold/resource/crd.go
  pkg/scaffold/resource/doc.go
  pkg/scaffold/resource/group.go
  pkg/scaffold/resource/register.go
  pkg/scaffold/resource/resource.go
  pkg/scaffold/resource/role.go
  pkg/scaffold/resource/rolebinding.go
  pkg/scaffold/resource/types.go
  pkg/scaffold/resource/typestest.go
  pkg/scaffold/resource/version_suitetest.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#9 Scaffold a new Controller for an API
  pkg/scaffold/controller/add.go
  pkg/scaffold/controller/controller.go
  pkg/scaffold/controller/controller_suite_test.go
  pkg/scaffold/controller/controller_test.go
  pkg/scaffold/controller/controllersuitetest.go
  pkg/scaffold/controller/controllertest.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#10 Scaffold a new Controller-Manager for a Project
  pkg/scaffold/manager/apis.go
  pkg/scaffold/manager/cmd.go
  pkg/scaffold/manager/config.go
  pkg/scaffold/manager/controller.go
  pkg/scaffold/manager/dockerfile.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#14 Run generate in test.sh now that we don't check in generated files
  test.sh
Labels: cncf-cla: yes, size/XS

#15 Add pkg/scaffold/project tests
  PROJECT
  cmd/controller-scaffold/cmd/api.go
  cmd/controller-scaffold/cmd/project.go
  pkg/scaffold/input/input.go
  pkg/scaffold/project/boilerplate.go
  pkg/scaffold/project/gopkg.go
  pkg/scaffold/project/project.go
  pkg/scaffold/project/project_suite_test.go
  pkg/scaffold/project/project_test.go
  pkg/scaffold/project/projectutil/projectutil.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/scaffoldtest/scaffoldtest.go
  test.sh
  test/Gopkg.toml
  test/PROJECT
  test/vendor
Labels: approved, cncf-cla: yes, lgtm, size/XL

#16 godocbot: use controllerutil helper for owner reference
  examples/godocbot/Gopkg.lock
  examples/godocbot/pkg/controller/pullrequest/godoc_deployer.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/generator/certgenerator.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/generator/doc.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/generator/fake/certgenerator.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/generator/selfsigned.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/writer/certwriter.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/writer/doc.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/writer/fs.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/writer/multiple.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/cert/writer/secret.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/controller.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/admission/doc.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/examplecrd1.yaml
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/examplecrd2.yaml
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/ginkgo.go
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/notcrd.yaml
  examples/godocbot/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#19 Fix typo: kubeuilder -> kubebuilder
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
