Repository kubernetes-sigs/controller-tools, pull requests merged in 2018-12, with the labels that each got.

#107 Dockerfile: move manager to /, from /root/
  examples/godocbot/Dockerfile
  pkg/crd/generator/testData/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#106 Logic to support resource annotation for a given API type
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/generate/rbac/manifests.go
  pkg/generate/rbac/parser.go
  pkg/generate/rbac/parser_test.go
  pkg/generate/webhook/manifests.go
  pkg/generate/webhook/parser.go
  pkg/generate/webhook/parser_test.go
  pkg/internal/codegen/parse/index.go
  pkg/internal/codegen/parse/util.go
  pkg/internal/general/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#112 Handle "intstr.IntOrString" use case for the generated openAPI validation
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#111 Include description in the OpenAPI schema under fields property
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#114 [travis] use go 1.11
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#115 :running: added PR templates
  .github/PULL_REQUEST_TEMPLATE/breaking_change.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/compat_feature.md
  .github/PULL_REQUEST_TEMPLATE/docs.md
  .github/PULL_REQUEST_TEMPLATE/other.md
  .github/pull_request_template.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#97 Refactor pkg/generate
  cmd/controller-gen/main.go
  pkg/generate/doc.go
  pkg/rbac/manifests.go
  pkg/rbac/parser.go
  pkg/rbac/parser_test.go
  pkg/webhook/internal/client.go
  pkg/webhook/internal/client_test.go
  pkg/webhook/internal/manager.go
  pkg/webhook/manifests.go
  pkg/webhook/parser.go
  pkg/webhook/parser_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 :bug: Fix description generation to work for all types of fields
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M
