Repository kubernetes-sigs/controller-tools, pull requests merged in 2018-08, with the labels that each got.

#58 controller-gen: derive apispkg from project-dir
  pkg/crd/generator/generator.go
  pkg/crd/util/util.go
  pkg/internal/codegen/parse/apis.go
  pkg/internal/codegen/parse/controllers.go
  pkg/internal/codegen/parse/parser.go
  pkg/internal/codegen/parse/rbac.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 controller-gen: added tests for crd generation
  Gopkg.lock
  Gopkg.toml
  pkg/crd/generator/generator.go
  pkg/crd/generator/generator_test.go
  pkg/crd/generator/testData/Dockerfile
  pkg/crd/generator/testData/Makefile
  pkg/crd/generator/testData/PROJECT
  pkg/crd/generator/testData/cmd/manager/main.go
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/config/default/kustomization.yaml
  pkg/crd/generator/testData/config/default/manager_image_patch.yaml
  pkg/crd/generator/testData/config/manager/manager.yaml
  pkg/crd/generator/testData/config/samples/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/hack/boilerplate.go.txt
  pkg/crd/generator/testData/pkg/apis/addtoscheme_fun_v1alpha1.go
  pkg/crd/generator/testData/pkg/apis/apis.go
  pkg/crd/generator/testData/pkg/apis/fun/group.go
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/doc.go
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/register.go
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/zz_generated.deepcopy.go
  pkg/crd/generator/testData/pkg/controller/controller.go
  pkg/crd/generator/testData/vendor
  pkg/internal/codegen/parse/crd.go
  pkg/scaffold/scaffold.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#68 Scaffolded project to use versioned pkgs of controller-*
  pkg/scaffold/project/gopkg.go
  test/Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 made storage test for types to be scope aware
  pkg/scaffold/resource/typestest.go
  test/pkg/apis/creatures/v2alpha1/kraken_types_test.go
  test/pkg/apis/crew/v1/firstmate_types_test.go
  test/pkg/apis/policy/v1beta1/healthcheckpolicy_types_test.go
  test/pkg/apis/ship/v1beta1/frigate_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#69 Feature: support scale sub resource by tag in controller-tools
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/util.go
  pkg/internal/codegen/parse/util_test.go
  pkg/internal/codegen/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#73 gas linter has been renamed to gosec
  pkg/scaffold/scaffold.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 removed type field from crd validation schema
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/internal/codegen/parse/crd.go
  test/config/crds/creatures_v2alpha1_kraken.yaml
  test/config/crds/crew_v1_firstmate.yaml
  test/config/crds/policy_v1beta1_healthcheckpolicy.yaml
  test/config/crds/ship_v1beta1_frigate.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
