Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-06, with the labels that each got.

#222 🐛 Generate deepcopy for all struct members
  pkg/deepcopy/traverse.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#219 🐛 Fix rbac example
  cmd/controller-gen/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 ✨ crd: add a resource scope marker
  pkg/crd/markers/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 Add ability to set default field requirement status
  pkg/crd/markers/package.go
  pkg/crd/markers/validation.go
  pkg/crd/parser.go
  pkg/crd/schema.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#229 :bug: ensure defaults are set for controller-gen all
  cmd/controller-gen/main.go
  pkg/rbac/manifests.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#226 :bug: Smarter allOf flattening/validation preservation
  Gopkg.lock
  go.mod
  go.sum
  pkg/crd/crd_suite_test.go
  pkg/crd/flatten.go
  pkg/crd/flatten_all_of_test.go
  pkg/crd/flatten_type_test.go
  pkg/crd/parser_integration_test.go
  pkg/crd/schema.go
  pkg/crd/spec.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/go.mod
  pkg/crd/testdata/go.sum
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#228 🐛Add FieldOnlyMarkers to AllDefinitions and update Nullable
  pkg/crd/markers/validation.go
  pkg/crd/parser_integration_test.go
  pkg/crd/testdata/README.md
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
