Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-10, with the labels that each got.

#332 :sparkles: Add a --version option to controller-gen
  cmd/controller-gen/main.go
  cmd/type-scaffold/main.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#331 :sparkles: Trim leading space from generated marker help `Details` field
  cmd/helpgen/main.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/zz_generated.markerhelp.go
  pkg/genall/zz_generated.markerhelp.go
  pkg/webhook/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#335 Add missing trailing : to :sparkles: in the PR template
  .github/pull_request_template.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 :sparkles: s/kubebuilder:validation:Default/kubebuilder:Default/
  pkg/crd/markers/validation.go
  pkg/crd/testdata/cronjob_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#325 ✨ Use +kubebuilder:skip to skip package
  pkg/crd/markers/package.go
  pkg/crd/parser.go
  pkg/crd/parser_integration_test.go
  pkg/crd/testdata/internal_version/go.mod
  pkg/crd/testdata/internal_version/go.sum
  pkg/crd/testdata/internal_version/internal_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#277 🐛 Add apiextensions JSON type to known_types.go
  pkg/crd/known_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#341 📖 Fix documentation for mutating webhooks.
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 🏃 Add pattern validator test
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#338 :sparkles: add controller-gen attribution info to CRD
  pkg/crd/gen.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M
