Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-08, with the labels that each got.

#260 Add a new `namespace` field into the RBAC marker
  pkg/rbac/parser.go
  pkg/rbac/parser_integration_test.go
  pkg/rbac/testdata/controller.go
  pkg/rbac/testdata/role.yaml
  pkg/rbac/zz_generated.markerhelp.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#290 :bug: Collapse Common CRD Version Info
  Gopkg.lock
  pkg/crd/crd_spec_test.go
  pkg/crd/spec.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/L

#268 🐛 Handle the error type in crd gen
  pkg/crd/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#299 Limiting description of fields in CRD's OpenAPI Schema
  pkg/crd/desc_visitor.go
  pkg/crd/desc_visitor_test.go
  pkg/crd/gen.go
  pkg/crd/parser_integration_test.go
  pkg/crd/spec.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#305 :book: generate help for maxDecLen commandline parameter
  pkg/crd/gen.go
  pkg/crd/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#306 ⚠Change autogenerated / do not edit comment in deepcopy files
  cmd/helpgen/main.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/zz_generated.markerhelp.go
  pkg/deepcopy/gen.go
  pkg/deepcopy/testdata/zz_generated.deepcopy.go
  pkg/deepcopy/zz_generated.markerhelp.go
  pkg/genall/zz_generated.markerhelp.go
  pkg/rbac/zz_generated.markerhelp.go
  pkg/webhook/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#308 ✨ Add skipversion marker to selectively exclude CRD versions
  pkg/crd/markers/crd.go
  pkg/crd/markers/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/M
