Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-07, with the labels that each got.

#246 :bug: use github.com/gobuffalo/flect
  .travis.yml
  Gopkg.lock
  cmd/controller-gen/main.go
  go.mod
  go.sum
  pkg/crd/spec.go
  pkg/genall/output.go
  pkg/typescaffold/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#241 Add a `sync.Mutex` field into TypeChecker
  pkg/loader/refs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#235 Merge rules in config/rbac/role.yaml
  pkg/rbac/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#234 Add support for arrays as map values into pkg/crd
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#254 :bug: special-casing metav1.ObjectMeta.
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#252 Make the `Path` field of the "+kubebuilder:resource" marker optional
  pkg/crd/markers/crd.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#255 Revert ":bug: special-casing metav1.ObjectMeta."
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#253 Avoid reordering Rules
  pkg/rbac/parser.go
  pkg/rbac/parser_integration_test.go
  pkg/rbac/rbac_suite_test.go
  pkg/rbac/testdata/README.md
  pkg/rbac/testdata/controller.go
  pkg/rbac/testdata/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#266 :warning: drop validation schema for objectmeta
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#248 :sparkles: Help!
  Gopkg.lock
  boilerplate.go.txt
  cmd/controller-gen/main.go
  cmd/helpgen/main.go
  go.mod
  go.sum
  pkg/crd/gen.go
  pkg/crd/markers/crd.go
  pkg/crd/markers/package.go
  pkg/crd/markers/register.go
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/zz_generated.markerhelp.go
  pkg/deepcopy/gen.go
  pkg/deepcopy/zz_generated.markerhelp.go
  pkg/genall/doc.go
  pkg/genall/genall.go
  pkg/genall/help/doc.go
  pkg/genall/help/pretty/doc.go
  pkg/genall/help/pretty/help.go
  pkg/genall/help/pretty/print.go
  pkg/genall/help/pretty/table.go
  pkg/genall/help/sort.go
  pkg/genall/help/types.go
  pkg/genall/options.go
  pkg/genall/output.go
  pkg/genall/zz_generated.markerhelp.go
  pkg/markers/doc.go
  pkg/markers/help.go
  pkg/markers/parse.go
  pkg/markers/reg.go
  pkg/markers/regutil.go
  pkg/rbac/parser.go
  pkg/rbac/zz_generated.markerhelp.go
  pkg/webhook/parser.go
  pkg/webhook/zz_generated.markerhelp.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#265 :bug: Avoid data race on package type data
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#274 :bug: CLI Help issues and Marker Registration Regression
  cmd/controller-gen/main.go
  pkg/crd/markers/validation.go
  pkg/crd/testdata/README.md
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/genall/help/pretty/help.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#289 :running: drop the useless PROJECT file
  PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/XS

#271 ✨ Correctly format metav1.MicroTime as date-time
  pkg/crd/known_types.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#269 ✨ Fix "encountered" typo in error message
  pkg/crd/schema.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#267 Sort the CRD Versions in the generated CRD and set `crd.Spec.Version` explicitly
  pkg/crd/spec.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
