Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-04, with the labels that each got.

#177 :sparkles: pkg/crd/generator: defer chdir back to calling dir
  pkg/crd/generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#176 :bug: Restore Gopkg.toml
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  test.sh
  vendor/github.com/gogo/protobuf/proto/decode.go
  vendor/github.com/gogo/protobuf/proto/deprecated.go
  vendor/github.com/gogo/protobuf/proto/extensions.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/message_set.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/spf13/afero/unionFile.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#184 Remove dependency on PROJECT file for CRD generator
  pkg/crd/generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#187 ⚠Rewriting CRD generator to use built-in go type inferences
  pkg/crd/v2/crd.go
  pkg/crd/v2/definition_checker.go
  pkg/crd/v2/definition_pruner.go
  pkg/crd/v2/embed.go
  pkg/crd/v2/flattener.go
  pkg/crd/v2/generator.go
  pkg/crd/v2/multiversion.go
  pkg/crd/v2/parser.go
  pkg/crd/v2/types.go
  pkg/crd/v2/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#188 Add a test for single version CRD generator
  pkg/crd/v2/crd.go
  pkg/crd/v2/embed.go
  pkg/crd/v2/generator.go
  pkg/crd/v2/multiversion.go
  pkg/crd/v2/parser.go
  pkg/crd/v2/singleversion.go
  pkg/crd/v2/singleversion_test.go
  pkg/crd/v2/validation.go
  pkg/crd/v2/writer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#189 add a bit more tests for CRD
  pkg/crd/v2/multiversion_test.go
  pkg/crd/v2/parser.go
  pkg/crd/v2/singleversion.go
  pkg/crd/v2/singleversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#193 drop annotation in webhook manifests generator
  pkg/webhook/generator.go
  pkg/webhook/generator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#194 :bug: Fix import path for references to testData/
  testData/Dockerfile
  testData/Makefile
  testData/PROJECT
  testData/cmd/manager/main.go
  testData/go.mod
  testData/pkg/apis/addtoscheme_fun_v1alpha1.go
  testData/pkg/apis/fun/v1alpha1/doc.go
  testData/pkg/apis/fun/v1alpha1/register.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#191 validate webhook options after parsing
  pkg/webhook/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#179 🐛 fix windows filepath compatibility
  pkg/crd/generator/generator.go
  pkg/crd/util/util.go
  pkg/webhook/generator.go
  pkg/webhook/manifests.go
  pkg/webhook/writer.go
Labels: approved, cncf-cla: yes, lgtm, size/S
