Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-05, with the labels that each got.

#203 :bug: Fix incompatible CRDs
  pkg/crd/gen.go
  pkg/crd/markers/crd.go
  pkg/crd/spec.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#208 :sparkles: write multiple webhooks in one file and add defaulting
  pkg/crd/gen.go
  pkg/genall/genall.go
  pkg/rbac/parser.go
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#209 :bug: Fix panic on missing import in ref checker
  pkg/crd/gen.go
  pkg/loader/refs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 :sparkles: CRD storage version marker
  pkg/crd/markers/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#180 Support 1.14 +nullable tag
  pkg/crd/markers/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 ✨ controller-tools-maintainers is an empty alias
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 :bug: Ensure same-line last-comment case is handled
  pkg/markers/collect.go
  pkg/markers/markers_suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
