Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-09, with the labels that each got.

#303 Treat unstructured.Unstructured type as known type.
  pkg/crd/known_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#311 :sparkles: pkg/crd/spec.go: set default ListKind and Singular CRD names
  pkg/crd/spec.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#314 📖Update builtinToType comments to explain support for int32 and int64
  pkg/crd/schema.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#276 :warning: Update Kubernetes client libraries to 1.15.0 release
  .golangci.yml
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  pkg/schemapatcher/testdata/expected/legacy-example-crd.yaml
  pkg/schemapatcher/testdata/expected/legacy-unchanged-crd.yaml
  pkg/schemapatcher/testdata/go.sum
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#318 :sparkles: Factor code common to both types of webhooks into methods
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#319 :warning: Update kube deps to 1.16
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  pkg/schemapatcher/testdata/expected/kubebuilder-example-crd.yaml
  pkg/schemapatcher/testdata/expected/kubebuilder-unchanged-crd.yaml
  pkg/schemapatcher/testdata/expected/legacy-example-crd.yaml
  pkg/schemapatcher/testdata/expected/legacy-unchanged-crd.yaml
  pkg/schemapatcher/testdata/go.mod
  pkg/schemapatcher/testdata/go.sum
  pkg/schemapatcher/testdata/manifests/kubebuilder-example-crd.yaml
  pkg/schemapatcher/testdata/manifests/legacy-example-crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#322 :bug: promote version-specific CRD fields when only one version
  pkg/crd/crd_spec_test.go
  pkg/crd/spec.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#329 support maps in marker marker parsing
  pkg/markers/parse.go
  pkg/markers/parse_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#323 :sparkles: Add a marker to support field defaulting in crd schema
  pkg/crd/markers/doc.go
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/markers/parse.go
  pkg/markers/parse_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
