Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-11, with the labels that each got.

#358 :bug: Use pointers to generators everywhere
  pkg/genall/genall.go
  pkg/genall/options.go
  pkg/schemapatcher/gen_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#345 Add x-kubernetes-{embedded-resource,preserve-unknown-fields} support
  go.mod
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#360 :bug: Update known_types to add x-kubernetes-int-or-string for intStr
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#355 :book: CRD scope
  pkg/crd/markers/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#362 :bug: preserveUnknownFields: true on v1beta1, option
  pkg/crd/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/S
