Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-03, with the labels that each got.

#160 crd-gen: add RawExtension support
  pkg/internal/codegen/parse/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#161 :warning: Change to use the default rule set for Pluralize.
  pkg/internal/codegen/parse/index.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Configuration options
  cmd/controller-gen/main.go
  pkg/rbac/manifests.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, sig/api-machinery, size/M

#158 crd-gen: fix intOrString type
  pkg/internal/codegen/parse/crd.go
  testData/config/crds/fun_v1alpha1_toy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 crd-gen: apply tags to special types, kube types and maps as well
  pkg/internal/codegen/parse/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#169 Revert "✨Add flags to customize API path and contexts"
  cmd/crd/cmd/generate.go
  pkg/crd/generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#164 ✨ update the kubernetes dependencies to the latest patch release of 1.13 - 1.13.4
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#171 :bug: skip generating webhooks when no markers defined
  pkg/webhook/manifests.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 Add APIsPath and APIsPkg crd generator variables w/ defaults
  cmd/controller-gen/main.go
  cmd/crd/cmd/generate.go
  pkg/crd/generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#174 Fix OpenAPI type for resource.Quantity fields
  pkg/internal/codegen/parse/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/S
