Repository kubernetes-sigs/controller-tools, pull requests merged in 2019-12, with the labels that each got.

#368 :book: update URL in README.md
  pkg/crd/testdata/README.md
  pkg/deepcopy/testdata/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#351 :bug: controller-gen panics when encountering an import loop
  pkg/loader/loader.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, size/XS

#379 :sparkles: Update dependences to kubernetes 1.17.0
  go.mod
  go.sum
Labels: approved, area/dependency, cncf-cla: yes, lgtm, size/L
