Repository kubernetes-sigs/controller-tools, pull requests merged in 2020-06, with the labels that each got.

#428 🐛 Fix flattening chains of references to references
  pkg/crd/flatten_type_test.go
  pkg/crd/schema_visitor.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#452 :bug: Update go/packages version
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#449 ✨ Add support for AllowDangerousTypes crd flag (enables float support)
  pkg/crd/gen.go
  pkg/crd/parser.go
  pkg/crd/schema.go
  pkg/crd/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/M

#451 🏃Move pwittrock from emeritus approvers to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
