Repository kubernetes-sigs/controller-tools, pull requests merged in 2020-10, with the labels that each got.

#497 :seedling: Add PR title/description checking
  .github/workflows/verify.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#498 :book: Add versioning guidelines
  README.md
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#505 :bug: Don't generate schema with `Any` in it, its not supported
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#495 🐛 Remove unneeded caBundle: Cg== value
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/webhook/parser.go
  pkg/webhook/testdata/manifests.v1beta1.yaml
  pkg/webhook/testdata/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
