Repository kubernetes-sigs/controller-tools, pull requests merged in 2020-02, with the labels that each got.

#405 :bug: use map in FindKubeKinds
  pkg/crd/gen.go
  pkg/schemapatcher/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#407 🏃Add vincepri to maintainers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 ⚠ Bump to go 1.13
  .travis.yml
  go.mod
  go.sum
  pkg/crd/conv.go
  pkg/crd/testdata/go.mod
  pkg/deepcopy/testdata/go.mod
  pkg/genall/options.go
  pkg/markers/parse.go
  pkg/schemapatcher/gen.go
  pkg/schemapatcher/internal/yaml/convert.go
  pkg/schemapatcher/internal/yaml/nested.go
  pkg/schemapatcher/testdata/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#408 ✨ Add support for MatchPolicy in webhook marker
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/S
