Repository kubernetes-sigs/controller-tools, pull requests merged in 2020-01, with the labels that each got.

#382 ✨ update flect library to v0.2.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#381 ✨ Change Quantity type to int-or-string
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#344 ✨ Do not create empty webhook/manifests.yaml file
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#397 :running: Clean up OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#353 Extend webhook marker documentation
  pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/S
