Repository kubernetes-sigs/controller-tools, pull requests merged in 2020-09, with the labels that each got.

#481 ✨ Remove 'default' fields from v1beta1 CRDs
  pkg/crd/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#480 ✨ Set default value for corev1.Protocol type if not already specified
  pkg/crd/known_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#470 ✨ feat: parse negative integers
  pkg/crd/markers/validation.go
  pkg/markers/parse.go
  pkg/markers/parse_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#488 ✨ add min/max properties validation
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#493 :bug: Don't allow generators to interfere with eachother's type checking
  pkg/crd/gen.go
  pkg/crd/parser.go
  pkg/crd/schema_visitor.go
  pkg/deepcopy/deepcopy_integration_test.go
  pkg/deepcopy/gen.go
  pkg/deepcopy/testdata/cronjob_types.go
  pkg/deepcopy/testdata/legacy_deepcopy_cases.go
  pkg/deepcopy/testdata/zz_generated.deepcopy.go
  pkg/deepcopy/traverse.go
  pkg/genall/genall.go
  pkg/loader/errors.go
  pkg/loader/refs.go
  pkg/schemapatcher/gen.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L
