Repository kubernetes-sigs/controller-tools, pull requests merged in 2021-09, with the labels that each got.

#608 🐛 Allow pattern usage for IntOrString fields
  pkg/crd/markers/validation.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#614 :running: Run linting in CI
  .travis.yml
  Makefile
  test.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#611 🐛 Fix int or string pattern application
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#606 🏃add joelanford to controller-tools-maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#616 :running: Add alvaroaleman to maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#573 🏃 Improve error message for list or map type
  pkg/crd/markers/topology.go
Labels: cncf-cla: yes, lifecycle/rotten, approved, size/XS, lgtm

#518 🐛 Allow nested maps in Go types
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#618 :bug: Be more helpful with floats when allowDangerousTypes=false
  pkg/crd/schema.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#617 ✨ Allow maps of arrays of non-string types
  pkg/crd/schema.go
  pkg/crd/schema_test.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#626 🐛 Updating WriteYAML to not add empty line to start files
  pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
  pkg/crd/testdata/gen/bar.example.com_foos.yaml
  pkg/genall/genall.go
  pkg/webhook/parser_integration_test.go
  pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
  pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
  pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
  pkg/webhook/testdata/manifests.yaml
  pkg/webhook/testdata/valid/manifests.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm
