Repository kubernetes-sigs/controller-tools, pull requests merged in 2021-01, with the labels that each got.

#534 :warning: update dependencies to v1.19.2
  .run-controller-gen.sh
  go.mod
  go.sum
  pkg/crd/gen_integration_test.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
  pkg/crd/testdata/gen/bar.example.com_foos.yaml
  pkg/crd/testdata/gen/foo_types.go
  pkg/crd/testdata/go.mod
  pkg/crd/testdata/go.sum
  pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
  pkg/crd/testdata/plural/types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/deepcopy/testdata/go.mod
  pkg/deepcopy/testdata/go.sum
  pkg/schemapatcher/testdata/expected/kubebuilder-example-crd.v1.yaml
  pkg/schemapatcher/testdata/expected/kubebuilder-example-crd.yaml
  pkg/schemapatcher/testdata/expected/kubebuilder-unchanged-crd.v1beta1.yaml
  pkg/schemapatcher/testdata/expected/kubebuilder-unchanged-crd.yaml
  pkg/schemapatcher/testdata/expected/legacy-example-crd.yaml
  pkg/schemapatcher/testdata/expected/legacy-unchanged-crd.yaml
  pkg/schemapatcher/testdata/go.mod
  pkg/schemapatcher/testdata/go.sum
  pkg/schemapatcher/testdata/manifests/kubebuilder-example-crd.v1.yaml
  pkg/schemapatcher/testdata/manifests/kubebuilder-example-crd.yaml
  pkg/schemapatcher/testdata/manifests/legacy-example-crd.yaml
  pkg/webhook/conv.go
  pkg/webhook/parser.go
  pkg/webhook/parser_integration_test.go
  pkg/webhook/testdata/go.mod
  pkg/webhook/testdata/go.sum
  pkg/webhook/testdata/manifests.v1beta1.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#538 🏃 Update dependencies to Kubernetes v1.20.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#528 :sparkles: Add crd:validation:Schemaless marker
  .golangci.yml
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
