Repository kubernetes-sigs/controller-tools, pull requests merged in 2022-11, with the labels that each got.

#723 🐛 Update CI golangci-lint checks to avoid deprecated linters
  test.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm

#727 🏃 add go reference badge
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#725 :bug: return a bit more verbosy error messages for go-package errors
  pkg/loader/loader.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#691 ✨ Support api-approved annotation for CRD with k8s group
  pkg/crd/markers/crd.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/parser_integration_test.go
  pkg/crd/spec.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#736 🌱 : dependabot addition
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#743 :seedling: Add :seedling: to dependabot commit message
  .github/dependabot.yml
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/XS, lgtm
