Repository kubernetes-sigs/controller-tools, pull requests merged in 2022-04, with the labels that each got.

#648 🐛 Fixed panic when parsing selector expressions containing composite literals
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/loader/refs.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#666 ✨ Bump to k8s.io v1.24.0-rc.1
  go.mod
  go.sum
  pkg/version/version.go
  test.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#660 🏃 Update to Flect v0.2.5
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
