Repository kubernetes-sigs/controller-tools, pull requests merged in 2022-09, with the labels that each got.

#722 ✨ Upgrade to go 1.19 and fix CI
  cmd/controller-gen/main.go
  cmd/type-scaffold/main.go
  go.mod
  go.sum
  pkg/crd/doc.go
  pkg/crd/known_types.go
  pkg/crd/markers/doc.go
  pkg/crd/markers/topology.go
  pkg/crd/spec.go
  pkg/genall/doc.go
  pkg/genall/help/pretty/doc.go
  pkg/loader/doc.go
  pkg/loader/loader.go
  pkg/markers/collect.go
  pkg/markers/doc.go
  pkg/markers/reg.go
  pkg/markers/zip.go
  pkg/rbac/parser.go
  pkg/version/version.go
  pkg/webhook/parser.go
  test.sh
Labels: cncf-cla: yes, size/XXL, approved, lgtm, ok-to-test

#712 📖 Update controller-gen CLI documentation for better info regards paths argument
  pkg/genall/options.go
  pkg/genall/zz_generated.markerhelp.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#724 🐛 Ensure schemapatcher does not error when non CRD yaml files are present
  pkg/schemapatcher/gen.go
  pkg/schemapatcher/testdata/valid/example.cr.yaml
  pkg/schemapatcher/testdata/valid/random.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm
