Repository kubernetes-sigs/controller-tools, pull requests merged in 2022-05, with the labels that each got.

#619 🐛 Allow floating-point values in validations
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/parser_integration_test.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/markers/parse.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#663 :sparkles: Cross-module support for filesystem paths
  pkg/loader/loader.go
  pkg/loader/loader_suite_test.go
  pkg/loader/loader_test.go
  pkg/loader/testmod/dummy.go
  pkg/loader/testmod/go.mod
  pkg/loader/testmod/subdir1/dummy.go
  pkg/loader/testmod/subdir1/subdir1/dummy.go
  pkg/loader/testmod/subdir1/subdir2/dummy.go
  pkg/loader/testmod/subdir1/submod1/dummy.go
  pkg/loader/testmod/subdir1/submod1/go.mod
  pkg/loader/testmod/submod1/dummy.go
  pkg/loader/testmod/submod1/go.mod
  pkg/loader/testmod/submod1/subdir1/dummy.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#669 :sparkles: Bump k8s to 1.24.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#682 :bug: ci: fix golangci-lint installation
  test.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm
