Repository kubernetes-sigs/controller-tools, pull requests merged in 2023-01, with the labels that each got.

#544 ✨ Add header and year options for yaml generator
  pkg/crd/gen.go
  pkg/genall/genall.go
  pkg/rbac/parser.go
  pkg/webhook/parser.go
Labels: cncf-cla: yes, size/M, lifecycle/rotten, approved, lgtm

#764 :bug: fix index out of range panic when annotation is not in 'key=value' format
  pkg/crd/markers/crd.go
  pkg/crd/parser_integration_test.go
  pkg/crd/testdata/wrong_annotation_format/cronjob_types.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#768 :running: Bump k8s.io dependencies to 1.26.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm
