Repository kubernetes-sigs/controller-tools, pull requests merged in 2023-04, with the labels that each got.

#781 :book: fix typo: minimun -> minimum
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#798 🏃 Bump k8s.io dependencies to v0.27.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#779 🐛 Generate deterministic ordering for webhook manifests
  pkg/webhook/parser.go
  pkg/webhook/parser_integration_test.go
  pkg/webhook/testdata/valid-ordered/cronjob_types.go
  pkg/webhook/testdata/valid-ordered/manifests.yaml
  pkg/webhook/testdata/valid-ordered/webhook.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#799 ✨ Update and sync owners file w/ CR runtime
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#800 🐛 remove metadata.creationTimestamp when generating CRDs, RBAC, and webhooks
  pkg/crd/gen.go
  pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
  pkg/crd/testdata/gen/bar.example.com_foos.yaml
  pkg/crd/testdata/gen/zoo/bar.example.com_zooes.v1beta1.yaml
  pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
  pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
  pkg/genall/genall.go
  pkg/rbac/parser.go
  pkg/rbac/testdata/role.yaml
  pkg/webhook/parser.go
  pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
  pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
  pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
  pkg/webhook/testdata/manifests.yaml
  pkg/webhook/testdata/valid-ordered/manifests.yaml
  pkg/webhook/testdata/valid/manifests.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#801 🐛 release-0.11: remove metadata.creationTimestamp when generating CRDs, RBAC, and webhooks
  pkg/crd/gen.go
  pkg/crd/testdata/gen/bar.example.com_foos.v1beta1.yaml
  pkg/crd/testdata/gen/bar.example.com_foos.yaml
  pkg/crd/testdata/gen/zoo/bar.example.com_zooes.v1beta1.yaml
  pkg/crd/testdata/gen/zoo/bar.example.com_zooes.yaml
  pkg/crd/testdata/plural/plural.example.com_testquotas.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
  pkg/genall/genall.go
  pkg/rbac/parser.go
  pkg/rbac/testdata/role.yaml
  pkg/webhook/parser.go
  pkg/webhook/testdata/invalid-admissionReviewVersionsRequired/manifests.yaml
  pkg/webhook/testdata/invalid-sideEffects/manifests.yaml
  pkg/webhook/testdata/invalid-v1beta1NotSupported/manifests.yaml
  pkg/webhook/testdata/manifests.yaml
  pkg/webhook/testdata/valid/manifests.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#704 :sparkles: testdata/cronjob_types.go: add NestedStructWithSeveralFieldsDoubleMarked
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash, ok-to-test

#803 :sparkles:Upgrade to go 1.20
  go.mod
  pkg/crd/gen_integration_test.go
  pkg/crd/markers/crd.go
  pkg/deepcopy/traverse.go
  pkg/genall/output.go
  pkg/markers/parse.go
  pkg/typescaffold/scaffold.go
  test.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#802 🐛 Fix marker parsing
  pkg/markers/parse.go
  pkg/markers/parse_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#804 ⚠ Bump github.com/gobuffalo/flect from 0.3.0 to 1.0.2
  go.mod
  go.sum
  pkg/crd/gen_integration_test.go
  pkg/crd/testdata/gen/zoo/bar.example.com_zoos.v1beta1.yaml
  pkg/crd/testdata/gen/zoo/bar.example.com_zoos.yaml
  pkg/crd/testdata/gen/zoo/zoo_types.go
Labels: cncf-cla: yes, size/S, approved, lgtm
