Repository kubernetes-sigs/controller-tools, pull requests merged in 2024-08, with the labels that each got.

#1023 🏃 Bump k8s.io/* deps to v1.31.0-rc.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1024 ✨Release envtest v1.30.3
  hack/envtest/_matrix/v1.30.3.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1026 ✨ Publish controller-gen binaries on release
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/release.yaml
  Makefile
Labels: cncf-cla: yes, size/M, approved, lgtm

#998 🐛 Fix XValidations flattening
  pkg/crd/flatten.go
  pkg/crd/flatten_all_of_test.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#1020 🌱 Add action to approve actions if ok-to-test is set
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1021 🏃 Enforce go mod tidy via "test" presubmit
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1022 📖 Document compatibility with k8s.io/*, client-go and Go
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#1031 ✨ Bump k8s.io/* deps to v1.31.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#1032 ✨ Release envtest v1.31.0
  hack/envtest/_matrix/v1.31.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1035 🐛 Fix duplicate default value when generating CRDs with corev1.Protocol
  pkg/crd/known_types.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/go.mod
  pkg/crd/testdata/go.sum
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1038 🏃 Rename default branch to main
  .github/workflows/golangci-lint.yml
  .github/workflows/tools-releases.yml
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1044 🐛 rbac: fix adding nonResourceURLs including normalisation
  pkg/rbac/parser.go
  pkg/rbac/testdata/controller.go
  pkg/rbac/testdata/role.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1045 🐛 rbac: fix deduplication of core group and add test coverage
  pkg/rbac/parser.go
  pkg/rbac/testdata/controller.go
  pkg/rbac/testdata/role.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm
