Repository kubernetes-sigs/controller-tools, pull requests merged in 2024-07, with the labels that each got.

#1003 :running: use ptr package
  go.mod
  pkg/crd/known_types.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#1000 :sparkles: Make the anonymous field of the groupName marker optional
  pkg/crd/markers/package.go
  pkg/crd/markers/register.go
  pkg/crd/parser_integration_test.go
  pkg/crd/testdata/nogroup/types.go
  pkg/crd/testdata/testdata._cronjobs.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1007 ✨ Release envtest v1.30.2
  hack/envtest/_matrix/v1.30.2.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1011 ✨ Release envtest v1.31.0-beta.0
  hack/envtest/_matrix/v1.31.0-beta.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1016 📖 Fix a typo in comment in validation.go
  pkg/crd/markers/validation.go
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/XS, lgtm
