Repository kubernetes-sigs/controller-tools, pull requests merged in 2024-05, with the labels that each got.

#944 :sparkles: add support for kubernetes +required annotations
  pkg/crd/markers/validation.go
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#937 ✨ rbac: deduplicate having the same groups, resourceNames, URLs and Verbs
  pkg/rbac/parser.go
  pkg/rbac/parser_integration_test.go
  pkg/rbac/testdata/controller.go
  pkg/rbac/testdata/role.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#938 ✨ Add support for +default markers
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/markers/parse.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#963 ✨ Release envtest v1.25.0
  hack/envtest/_matrix/v1.25.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#968 ✨ Release envtest v1.25.0 (II)
  hack/envtest/_matrix/v1.25.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#962 ✨ Release envtest v1.26.0
  hack/envtest/_matrix/v1.26.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#958 ✨ Release envtest v1.29.0
  hack/envtest/_matrix/v1.29.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#961 ✨ Release envtest v1.26.1
  hack/envtest/_matrix/v1.26.1.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#957 ✨ Release envtest v1.29.1
  hack/envtest/_matrix/v1.29.1.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#964 ✨ Release envtest v1.24.2
  hack/envtest/_matrix/v1.24.2.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#965 ✨ Release envtest v1.24.1
  hack/envtest/_matrix/v1.24.1.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#978 🌱 Promotion of envtest release for Kubernetes v1.28.3
  envtest-releases.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#979 ✨ Release envtest v1.23.5
  hack/envtest/_matrix/v1.23.5.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm
