Repository kubernetes-sigs/controller-tools, pull requests merged in 2024-04, with the labels that each got.

#898 :sparkles: pkg/crd: support validating internal list items on list types
  pkg/crd/markers/register.go
  pkg/crd/markers/validation.go
  pkg/crd/schema.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#901 🏃 Bump k/k to v1.30.0-rc.1 & Go to 1.22
  .golangci.yml
  go.mod
  go.sum
  pkg/loader/refs.go
  test.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#902 :seedling: Update golangci-lint, Makefile, Actions
  .github/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/verify.yml
  .gitignore
  Makefile
  hack/go-install.sh
  hack/tools/.keep
  pkg/crd/gen.go
  pkg/deepcopy/gen.go
  pkg/genall/options.go
  pkg/loader/loader.go
  pkg/markers/collect.go
  pkg/rbac/parser.go
  pkg/schemapatcher/gen.go
  pkg/typescaffold/resource.go
  pkg/version/version.go
  pkg/webhook/parser.go
  test.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#906 :sparkles: Build and publish Kubernetes envtest tools as packages
  .github/workflows/tools-releases.yml
  hack/envtest/_matrix/v1.28.0.yaml
  hack/envtest/_matrix/v1.29.3.yaml
  hack/envtest/darwin/Dockerfile
  hack/envtest/linux/Dockerfile
  hack/envtest/windows/Dockerfile
Labels: cncf-cla: yes, size/L, approved, lgtm

#908 ✨ Add github action to package envtest binaries in releases
  .github/workflows/tools-releases.yml
  .gitignore
  Makefile
  envtest-releases.yaml
  hack/envtest/_matrix/v1.28.0.yaml
  hack/envtest/darwin/Dockerfile
  hack/envtest/linux/Dockerfile
  hack/envtest/update-releases.sh
  hack/envtest/windows/Dockerfile
Labels: cncf-cla: yes, size/L, approved, lgtm

#918 🌱 Adjust branches for github actions
  .github/workflows/golangci-lint.yml
  .github/workflows/tools-releases.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#919 ✨ Release envtest v1.28.0
  hack/envtest/_matrix/v1.28.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#921 :seedling: Automatically release, fixup selfLink in camelCase
  .github/workflows/tools-releases.yml
  envtest-releases.yaml
  hack/envtest/update-releases.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#922 :seedling: Release envtest-v1.29.4
  hack/envtest/_matrix/v1.29.4.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#924 ✨ Release envtest v1.30.0
  hack/envtest/_matrix/v1.30.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#926 ✨ Bump to k8s.io/* v1.30
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#912 :sparkles: crd: allow specifying spec.preserveUnknownFields
  pkg/crd/gen.go
  pkg/crd/gen_integration_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#927 ✨ feat(crdvalidation): add messageExpression support to XValidation marker
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/zz_generated.markerhelp.go
  pkg/deepcopy/zz_generated.markerhelp.go
  pkg/genall/zz_generated.markerhelp.go
  pkg/rbac/zz_generated.markerhelp.go
  pkg/schemapatcher/zz_generated.markerhelp.go
  pkg/webhook/zz_generated.markerhelp.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#932 ✨ Add FieldPath and Reason to XValidation marker
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm
