Repository kubernetes-sigs/controller-tools, pull requests merged in 2025-05, with the labels that each got.

#1201 ✨ Release envtest v1.33.0 (try 2)
  hack/envtest/_matrix/v1.33.0.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1202 🌱 Promotion of envtest release for Kubernetes v1.33.0
  envtest-releases.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#1203 ⚠️ Bump to k8s.io/* v0.33.0
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
  pkg/applyconfiguration/testdata/cronjob/go.mod
  pkg/applyconfiguration/testdata/cronjob/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
