Repository kubernetes-sigs/controller-tools, pull requests merged in 2025-09, with the labels that each got.

#1274 🐛 Stop setting invalid formats int32/int64 for integer types
  pkg/crd/schema.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1275 🐛 Revert "Stop setting invalid formats int32/int64 for integer types"
  pkg/crd/schema.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
  pkg/crd/testdata/testdata.kubebuilder.io_jobs.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1280 🌱Release envtest v1.34.1
  hack/envtest/_matrix/v1.34.1.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1281 🌱chore: Update golangci-lint version to v2.4.0
  .github/workflows/golangci-lint.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1285 🌱 Promotion of envtest release for Kubernetes v1.34.1
  envtest-releases.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#1282 ✨ Allow title to be set on a type
  pkg/crd/markers/validation.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
