Repository kubernetes-sigs/controller-tools, pull requests merged in 2025-02, with the labels that each got.

#1134 🌱chore: Add golangci-lint linters
  .golangci.yml
  cmd/controller-gen/main.go
  pkg/crd/desc_visitor.go
  pkg/crd/desc_visitor_test.go
  pkg/crd/flatten.go
  pkg/crd/flatten_all_of_test.go
  pkg/crd/flatten_type_test.go
  pkg/crd/gen.go
  pkg/crd/gen_integration_test.go
  pkg/crd/known_types.go
  pkg/crd/markers/crd.go
  pkg/crd/markers/topology.go
  pkg/crd/markers/validation.go
  pkg/crd/parser.go
  pkg/crd/parser_integration_test.go
  pkg/crd/schema.go
  pkg/crd/spec.go
  pkg/deepcopy/deepcopy_integration_test.go
  pkg/deepcopy/traverse.go
  pkg/genall/genall.go
  pkg/genall/help/pretty/help.go
  pkg/genall/help/pretty/table.go
  pkg/genall/options.go
  pkg/loader/errors.go
  pkg/loader/loader_test.go
  pkg/loader/testutils/helpers.go
  pkg/markers/collect_test.go
  pkg/markers/markers_suite_test.go
  pkg/markers/parse.go
  pkg/markers/parse_test.go
  pkg/markers/zip.go
  pkg/rbac/parser.go
  pkg/rbac/parser_integration_test.go
  pkg/schemapatcher/gen.go
  pkg/schemapatcher/gen_integration_test.go
  pkg/schemapatcher/internal/yaml/delete_test.go
  pkg/version/version_test.go
  pkg/webhook/parser.go
  pkg/webhook/parser_integration_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#1150 :sparkles: markers: add support for optionalOldSelf in XValidation marker
  pkg/crd/markers/validation.go
  pkg/crd/markers/zz_generated.markerhelp.go
  pkg/crd/testdata/cronjob_types.go
  pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#1153 ⚠️Bump to k8s.io/* v0.33.0-alpha.2
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, tide/merge-method-squash, ok-to-test
